### ISSUE TITLE
Check Failed

### ISSUE THREAD

**Issue by GodOfMemes** [azer89/HelloVulkan#136]
For some reason, the check at line number 153 in VulkanDescriptor.cpp keeps failing. I check the result it gives off and the vkAllocateDescriptorSets is returning VK_ERROR_OUT_OF_POOL_MEMORY.

**Comment by azer89** [comment]
Which pipeline that calls `CreatePoolAndLayout()` ?

**Comment by azer89** [comment]
Usually the creation of descriptor pools is limited by available memory, so not sure why it failed.

**Comment by GodOfMemes** [comment]
By looking at the code there shouldn't be any reason for the pool to run out of memory unless I've overlooked something.

**Comment by GodOfMemes** [comment]
What GPU are you using so I can make sure my hypothesis for why it's not working on my system is correct

**Comment by azer89** [comment]
I'm using 3070 Laptop

**Comment by azer89** [comment]
I think I have found the problem, it seems that the pools are too small but NVidia cards are fine with it.

I have made a [PR here](https://github.com/azer89/HelloVulkan/pull/139)

**Comment by GodOfMemes** [comment]
Yep, that's the fix, based on the Vulkan spec it should crash on any driver vendor but Nvidia handles it automatically.

**Comment by azer89** [comment]
ok cool thanks for the confirmation, I'll approve your PRs soon
